---
title: "Residential_Analysis Compounded Daily"
author: "Steven Jordan"
date: "October 14, 2019"
output: html_document
---

```{r st}
library(zoo)
library(lubridate)
library(TSA)
library(psych)
library(forecast)

df = read.csv('C:/Users/sajor/Documents/Career/Class/Capstone/Daily Aggregated Files/consump_agg_sectors/consump_r_daily_agg.csv')

df$Date_Time = as.Date(df$Date_Time, format = "%m/%d/%Y")
df$Electricity_KW_HR_log = log(df$Electricity_KW_AVG)


```

```{r head}

head(df)
```



```{r exploration}
summary(df$Electricity_KW_AVG)
plot(df$Electricity_KW_AVG, type = "l", main="Retail Electricity Consumption",
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df$Electricity_KW_AVG)
qqline(df$Electricity_KW_AVG)
acf(df$Electricity_KW_AVG)
pacf(df$Electricity_KW_AVG)
eacf(df$Electricity_KW_AVG)

summary(df$Electricity_KW_HR_log)
plot(df$Electricity_KW_HR_log, type = "l", main="Retail Electricity Consumption",
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df$Electricity_KW_HR_log)
qqline(df$Electricity_KW_HR_log)
acf(df$Electricity_KW_HR_log)
pacf(df$Electricity_KW_HR_log)
eacf(df$Electricity_KW_HR_log)

```

```{r autoarima regular}
library(lmtest)

m1 = auto.arima(df$Electricity_KW_AVG, ic = "bic", trace = T, stationary =T)
Box.test(m1$residuals, lag=10, type="Ljung-Box") 
coeftest(m1) 
plot(m1$residuals) 

m2 = auto.arima(df$Electricity_KW_HR_log, ic = "bic", trace = T, stationary =T)
Box.test(m2$residuals, lag=10, type="Ljung-Box") 
coeftest(m2) 
plot(m2$residuals) 


```



```{r autoarima seasonal}

#Seasonal = 2
print('SEASONAL 2')
m1_2 = ts(df$Electricity_KW_AVG, frequency = 2)
m1_s2 = auto.arima(m1_2, ic = "bic", trace = T, stationary =T)
Box.test(m1_s2$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s2) 
plot(m1_s2$residuals) 

m2_2 = ts(df$Electricity_KW_HR_log, frequency = 2)
m2_s2 = auto.arima(m2_2, ic = "bic", trace = T, stationary =T)
Box.test(m2_s2$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s2) 
plot(m2_s2$residuals) 

print('SEASONAL 4')
m1_4 = ts(df$Electricity_KW_AVG, frequency = 4)
m1_s4 = auto.arima(m1_4, ic = "bic", trace = T, stationary =T)
Box.test(m1_s4$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s4) 
plot(m1_s4$residuals) 

m2_4 = ts(df$Electricity_KW_HR_log, frequency = 4)
m2_s4 = auto.arima(m2_4, ic = "bic", trace = T, stationary =T)
Box.test(m2_s4$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s4) 
plot(m2_s4$residuals) 

print('SEASONAL 5')
m1_5 = ts(df$Electricity_KW_AVG, frequency = 5)
m1_s5 = auto.arima(m1_5, ic = "bic", trace = T, stationary =T)
Box.test(m1_s5$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s5) 
plot(m1_s5$residuals) 

m2_5 = ts(df$Electricity_KW_HR_log, frequency = 5)
m2_s5 = auto.arima(m2_5, ic = "bic", trace = T, stationary =T)
Box.test(m2_s5$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s5) 
plot(m2_s5$residuals) 

print('SEASONAL 6')
m1_6 = ts(df$Electricity_KW_AVG, frequency = 6)
m1_s6 = auto.arima(m1_6, ic = "bic", trace = T, stationary =T)
Box.test(m1_s6$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s6) 
plot(m1_s6$residuals) 

m2_6 = ts(df$Electricity_KW_HR_log, frequency = 6)
m2_s6 = auto.arima(m2_6, ic = "bic", trace = T, stationary =T)
Box.test(m2_s6$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s6) 
plot(m2_s6$residuals) 

print('SEASONAL 7')
m1_7 = ts(df$Electricity_KW_AVG, frequency = 7)
m1_s7 = auto.arima(m1_7, ic = "bic", trace = T, stationary =T)
Box.test(m1_s7$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s7) 
plot(m1_s7$residuals) 

m2_7 = ts(df$Electricity_KW_HR_log, frequency = 7)
m2_s7 = auto.arima(m2_7, ic = "bic", trace = T, stationary =T)
Box.test(m2_s7$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s7) 
plot(m2_s7$residuals) 

print('SEASONAL 30')
m1_30 = ts(df$Electricity_KW_AVG, frequency = 30)
m1_s30 = auto.arima(m1_30, ic = "bic", trace = T, stationary =T)
Box.test(m1_s30$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s30) 
plot(m1_s30$residuals) 

m2_30 = ts(df$Electricity_KW_HR_log, frequency = 30)
m2_s30 = auto.arima(m2_30, ic = "bic", trace = T, stationary =T)
Box.test(m2_s30$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s30) 
plot(m2_s30$residuals) 

print('SEASONAL 31')
m1_31 = ts(df$Electricity_KW_AVG, frequency = 31)
m1_s31 = auto.arima(m1_31, ic = "bic", trace = T, stationary =T)
Box.test(m1_s31$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s31) 
plot(m1_s31$residuals) 

m2_31 = ts(df$Electricity_KW_HR_log, frequency = 31)
m2_s31 = auto.arima(m2_31, ic = "bic", trace = T, stationary =T)
Box.test(m2_s31$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s31) 
plot(m2_s31$residuals) 

print('SEASONAL 91')
m1_91 = ts(df$Electricity_KW_AVG, frequency = 91)
m1_s91 = auto.arima(m1_91, ic = "bic", trace = T, stationary =T)
Box.test(m1_s91$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s91) 
plot(m1_s91$residuals) 

m2_91 = ts(df$Electricity_KW_HR_log, frequency = 91)
m2_s91 = auto.arima(m2_91, ic = "bic", trace = T, stationary =T)
Box.test(m2_s91$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s91) 
plot(m2_s91$residuals) 

print('SEASONAL 122')
m1_122 = ts(df$Electricity_KW_AVG, frequency = 122)
m1_s122 = auto.arima(m1_122, ic = "bic", trace = T, stationary =T)
Box.test(m1_s122$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s122) 
plot(m1_s122$residuals) 

m2_122 = ts(df$Electricity_KW_HR_log, frequency = 122)
m2_s122 = auto.arima(m2_122, ic = "bic", trace = T, stationary =T)
Box.test(m2_s122$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s122) 
plot(m2_s122$residuals) 

print('SEASONAL 183')
m1_183 = ts(df$Electricity_KW_AVG, frequency = 183)
m1_s183 = auto.arima(m1_183, ic = "bic", trace = T, stationary =T)
Box.test(m1_s183$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s183) 
plot(m1_s183$residuals) 

m2_183 = ts(df$Electricity_KW_HR_log, frequency = 183)
m2_s183 = auto.arima(m2_183, ic = "bic", trace = T, stationary =T)
Box.test(m2_s183$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s183) 
plot(m2_s183$residuals) 

print('SEASONAL 365')
m1_365 = ts(df$Electricity_KW_AVG, frequency = 365)
m1_s365 = auto.arima(m1_365, ic = "bic", trace = T, stationary =T)
Box.test(m1_s365$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_s365) 
plot(m1_s365$residuals) 

m2_365 = ts(df$Electricity_KW_HR_log, frequency = 365)
m2_s365 = auto.arima(m2_365, ic = "bic", trace = T, stationary =T)
Box.test(m2_s365$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_s365) 
plot(m2_s365$residuals) 





```

