---
title: "Solar_Analysis Compounded Daily"
author: "Steven Jordan"
date: "October 14, 2019"
output: html_document
---

```{r st}
library(zoo)
library(lubridate)
library(TSA)
library(psych)
library(forecast)

df_solar = read.csv('C:/Users/sajor/Documents/Career/Class/Capstone/Daily Aggregated Files/solar_daily_agg.csv')

df_solar$Date_Time = as.Date(df_solar$Date_Time, format = "%m/%d/%Y")
df_solar2 = df_solar[-c(1),]
df_solar2$Electricity_KW_HR_log = diff(df_solar$Electricity_KW_HR_AVG)

```

```{r exploration}
summary(df_solar$Electricity_KW_HR_AVG)
plot(df_solar$Electricity_KW_HR_AVG, type = "l", main="Solar Electricity Production",
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df_solar$Electricity_KW_HR_AVG)
qqline(df_solar$Electricity_KW_HR_AVG)
acf(df_solar$Electricity_KW_HR_AVG)
pacf(df_solar$Electricity_KW_HR_AVG)
eacf(df_solar$Electricity_KW_HR_AVG)

summary(df_solar2$Electricity_KW_HR_log)
plot(df_solar2$Electricity_KW_HR_log, type = "l", main="Solar Electricity Production",
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df_solar2$Electricity_KW_HR_log)
qqline(df_solar2$Electricity_KW_HR_log)
acf(df_solar2$Electricity_KW_HR_log)
pacf(df_solar2$Electricity_KW_HR_log)
eacf(df_solar2$Electricity_KW_HR_log)

```

```{r autoarima regular}
library(lmtest)

m1_solar = auto.arima(df_solar$Electricity_KW_HR_AVG, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar) 
plot(m1_solar$residuals) 

m2_solar = auto.arima(df_solar2$Electricity_KW_HR_log, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar) 
plot(m2_solar$residuals) 


```



```{r autoarima seasonal}

#Seasonal = 2
print('SEASONAL 2')
m1_solar_2 = ts(df_solar$Electricity_KW_HR_AVG, frequency = 2)
m1_solar_s2 = auto.arima(m1_solar_2, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar_s2$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar_s2) 
plot(m1_solar_s2$residuals) 

m2_solar_2 = ts(df_solar2$Electricity_KW_HR_log, frequency = 2)
m2_solar_s2 = auto.arima(m2_solar_2, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar_s2$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar_s2) 
plot(m2_solar_s2$residuals) 

print('SEASONAL 4')
m1_solar_4 = ts(df_solar$Electricity_KW_HR_AVG, frequency = 4)
m1_solar_s4 = auto.arima(m1_solar_4, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar_s4$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar_s4) 
plot(m1_solar_s4$residuals) 

m2_solar_4 = ts(df_solar2$Electricity_KW_HR_log, frequency = 4)
m2_solar_s4 = auto.arima(m2_solar_4, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar_s4$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar_s4) 
plot(m2_solar_s4$residuals) 

print('SEASONAL 5')
m1_solar_5 = ts(df_solar$Electricity_KW_HR_AVG, frequency = 5)
m1_solar_s5 = auto.arima(m1_solar_5, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar_s5$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar_s5) 
plot(m1_solar_s5$residuals) 

m2_solar_5 = ts(df_solar2$Electricity_KW_HR_log, frequency = 5)
m2_solar_s5 = auto.arima(m2_solar_5, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar_s5$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar_s5) 
plot(m2_solar_s5$residuals) 

print('SEASONAL 30')
m1_solar_30 = ts(df_solar$Electricity_KW_HR_AVG, frequency = 30)
m1_solar_s30 = auto.arima(m1_solar_30, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar_s30$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar_s30) 
plot(m1_solar_s30$residuals) 

m2_solar_30 = ts(df_solar2$Electricity_KW_HR_log, frequency = 30)
m2_solar_s30 = auto.arima(m2_solar_30, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar_s30$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar_s30) 
plot(m2_solar_s30$residuals) 

print('SEASONAL 365')
m1_solar_365 = ts(df_solar$Electricity_KW_HR_AVG, frequency = 365)
m1_solar_s365 = auto.arima(m1_solar_365, ic = "bic", trace = T, stationary =T)
Box.test(m1_solar_s365$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_solar_s365) 
plot(m1_solar_s365$residuals) 

m2_solar_365 = ts(df_solar2$Electricity_KW_HR_log, frequency = 365)
m2_solar_s365 = auto.arima(m2_solar_365, ic = "bic", trace = T, stationary =T)
Box.test(m2_solar_s365$residuals, lag=10, type="Ljung-Box") 
coeftest(m2_solar_s365) 
plot(m2_solar_s365$residuals) 





```


