---
title: "Wind_Analysis Compounded Daily"
author: "Steven Jordan"
date: "October 14, 2019"
output: html_document
---

```{r st}
library(zoo)
library(lubridate)
library(TSA)
library(psych)
library(forecast)

df_wind = read.csv('C:/Users/sajor/Documents/Career/Class/Capstone/Processed Files2/Processed Files/Concatenated Files/production_windfarm_concat.csv')

df_wind$Date = as.Date(df_wind$Date, format = "%m/%d/%Y")
df_wind_d = aggregate(df_wind$Electricity_KW_HR, by=list(df_wind$Date), FUN=mean, na.rm=TRUE)
df_windspeed_d = aggregate(df_wind$Wind_Speed, by=list(df_wind$Date), FUN=mean, na.rm=TRUE)
names(df_wind_d) <- c("Date", "Electricity_KW_HR")
names(df_windspeed_d) <- c("Date", "Wind_Speed")
total = merge(df_wind_d, df_windspeed_d, by='Date')




```

```{r zeros}
plot(total$Wind_Speed, total$Electricity_KW_HR)


```


```{r differencing}
head(df_wind_d)
df_wind_d2 = df_wind_d


df_wind_d$Electricity_KW_HR_log = log(df_wind_d$Electricity_KW_HR)
head(df_wind_d)


```


```{r exploration}
summary(df_wind_d$Electricity_KW_HR)
plot(df_wind_d$Electricity_KW_HR, type = "l", main="Windfarm Electricity Production",
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df_wind_d$Electricity_KW_HR)
qqline(df_wind_d$Electricity_KW_HR)
acf(df_wind_d$Electricity_KW_HR)
pacf(df_wind_d$Electricity_KW_HR)
eacf(df_wind_d$Electricity_KW_HR)


summary(df_wind_d$Electricity_KW_HR_log)
plot(df_wind_d$Electricity_KW_HR_log, type = "l", main="Windfarm Electricity Production", 
     xlab="Day", ylab = "Mean KW/HR")
qqnorm(df_wind_d$Electricity_KW_HR_log)
qqline(df_wind_d$Electricity_KW_HR_log)
acf(df_wind_d$Electricity_KW_HR_log)
pacf(df_wind_d$Electricity_KW_HR_log)
eacf(df_wind_d$Electricity_KW_HR_log)
```
```{r autoarima regular}
library(lmtest)

m1_wind_d = auto.arima(df_wind_d$Electricity_KW_HR, ic = "bic", trace = T, stationary =T)
Box.test(m1_wind_d$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_wind_d) 
plot(m1_wind_d$residuals) 

#Autoarima
sm1_d_2 = ts(df_wind_d$Electricity_KW_HR, frequency = 2)
sm1_wind_d_2 = auto.arima(sm1_d_2, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_2$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_2) 
plot(sm1_wind_d_2$residuals) 

#Autoarima
sm1_d_3 = ts(df_wind_d$Electricity_KW_HR, frequency = 3)
sm1_wind_d_3 = auto.arima(sm1_d_3, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_3$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_3) 
plot(sm1_wind_d_3$residuals) 

#Autoarima
sm1_d_4 = ts(df_wind_d$Electricity_KW_HR, frequency = 4)
sm1_wind_d_4 = auto.arima(sm1_d_4, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_4$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_4) 
plot(sm1_wind_d_4$residuals) 

#Autoarima
sm1_d_6 = ts(df_wind_d$Electricity_KW_HR, frequency = 6)
sm1_wind_d_6 = auto.arima(sm1_d_6, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_6$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_6) 
plot(sm1_wind_d_6$residuals) 

#Autoarima
sm1_d_12 = ts(df_wind_d$Electricity_KW_HR, frequency = 12)
sm1_wind_d_12 = auto.arima(sm1_d_12, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_12$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_12) 
plot(sm1_wind_d_12$residuals) 

```

```{r autoarima log}

m1_wind_d_log = auto.arima(df_wind_d$Electricity_KW_HR_log, ic = "bic", trace = T, stationary =T)
Box.test(m1_wind_d_log$residuals, lag=10, type="Ljung-Box") 
coeftest(m1_wind_d_log) 
plot(m1_wind_d_log$residuals) 

#Autoarima
sm1_d_2_log = ts(df_wind_d$Electricity_KW_HR_log, frequency = 2)
sm1_wind_d_2_log = auto.arima(sm1_d_2_log, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_2_log$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_2_log) 
plot(sm1_wind_d_2_log$residuals) 

#Autoarima
sm1_d_3_log = ts(df_wind_d$Electricity_KW_HR_log, frequency = 3)
sm1_wind_d_3_log = auto.arima(sm1_d_3_log, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_3_log$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_3_log) 
plot(sm1_wind_d_3_log$residuals) 

#Autoarima
sm1_d_4_log = ts(df_wind_d$Electricity_KW_HR_log, frequency = 4)
sm1_wind_d_4_log = auto.arima(sm1_d_4_log, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_4_log$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_4_log) 
plot(sm1_wind_d_4_log$residuals) 

#Autoarima
sm1_d_6_log = ts(df_wind_d$Electricity_KW_HR_log, frequency = 6)
sm1_wind_d_6_log = auto.arima(sm1_d_6_log, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_6_log$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_6_log) 
plot(sm1_wind_d_6_log$residuals) 

#Autoarima
sm1_d_12_log = ts(df_wind_d$Electricity_KW_HR_log, frequency = 12)
sm1_wind_d_12_log = auto.arima(sm1_d_12_log, ic = "bic", trace = T, stationary =T)
Box.test(sm1_wind_d_12_log$residuals, lag=10, type="Ljung-Box") 
coeftest(sm1_wind_d_12_log) 
plot(sm1_wind_d_12_log$residuals) 

```


